[package]
name = "commercetools"
version = "0.1.0"
authors = ["Yann Simon <yann.simon@commercetools.com>"]

[dependencies]
hyper = "0.10"
hyper-openssl = "0.2"
chrono = "0.3"
log = "0.3"
error-chain = "0.8"

serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dev-dependencies]
env_logger = "0.4"

[dev-dependencies.clap]
version = "2.9"
default-features = false
features = [ "suggestions", "color" ]
