[package]
name = "commercetools"
version = "0.1.0"
authors = ["Yann Simon <yann.simon@commercetools.com>"]

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
chrono = "0.2"
log = "0.3"
error-chain = "0.2"

[dev-dependencies]
env_logger = "0.3"

[dev-dependencies.clap]
version = "2.9"
default-features = false
features = [ "suggestions", "color" ]
